# Generated by Django 4.2.3 on 2023-08-21 16:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0002_category_listing_comments_bid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="listing",
            old_name="starting_bid",
            new_name="price",
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="listing",
            name="image",
            field=models.ImageField(blank=True, upload_to="listings/"),
        ),
    ]
