# Generated by Django 4.2.3 on 2023-08-23 11:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0005_user_watchlist"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bid",
            old_name="item",
            new_name="listing",
        ),
        migrations.RenameField(
            model_name="bid",
            old_name="bid",
            new_name="price",
        ),
    ]
