# Generated by Django 4.2.3 on 2023-08-23 11:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0006_rename_item_bid_listing_rename_bid_bid_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="watchlist",
            field=models.ManyToManyField(
                blank=True, related_name="watchers", to="auctions.listing"
            ),
        ),
    ]
